apiVersion: v1
kind: Service
metadata:
  namespace: kube-logging
  name: elasticsearch-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200
