apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-ds
  namespace: kube-logging
  labels:
    app: fluent-bit-logging
spec:
  selector:
    matchLabels:
      app: fluent-bit-logging
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fluent-bit-logging
    spec:
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:1.6.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2020
          env:
            - name: FLUENT_ELASTICSEARCH_HOST ## 이 부분은 이제 만약 다 삭제할 시 다시 적어줘야 함
              # value: "es-node.test.com"
              value: "af55113334ef4439bb2e9ecb76468138-88912915.ap-northeast-2.elb.amazonaws.com"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
      serviceAccountName: fluent-bit-sa
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: "Exists"
          effect: "NoSchedule"