apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-csi
provisioner: ebs.csi.aws.com # ebs로 storageclass사용 시 생성 됨
parameters:
  type: gp2
volumeBindingMode: Immediate
reclaimPolicy: Delete
